
"Food": "Apple pie",
"Measure":"1 piece",
"FoodAr":"فطيره التفاح"
"measureAr": "قطعه",
"Grams": 100,
"Calories": 265,
"Protein": 12.5,
"protein": 2.4,
"Carbs" :37.1,


"food": "beef carpaccio",
"Measure": "1 piece",
"FoodAr": "كارباتشيو لحم البقر",
"MeasureAr": "قطعه",
"Grams": 100,
"Calories": 180
"Protein":25,
"Fat": 8,
"Carbs": 0,

"food": "caesar salad",
"Measure": "3 sp",
"FoodAr": "سلطه سيزر",
"MeasureAr": "3 معالق",
"Grams": 100,
"Calories": 46
"Protein" 3 g,
"Fat": 2,
"Carbs": 4,

"food": "cheesecake",
"Measure": "1 piece",
"FoodAr": "كعكه الجبن",
"MeasureAr":  "1 قطعه",
"Grams": 100,
"Calories": 321,
"Protein" 5.5 g,
"Fat": 22.5,
"Carbs": 25.5,


"food": "chicken wings",
"Measure": "1 piece",
"FoodAr": "اجنحه دجاج",
"Grams": 100,
"MeasureAr":  "1 قطعه",
"Calories": 124,
"Protein" 11.46,
"Fat": 8.3,
"Carbs": 0,

"food": "checolate cake",
"Measure": "1 piece",
"FoodAr": "كعكه الشيكولاته",
"Grams": 100,
"MeasureAr":  "1 قطعه",
"Calories": 367,
"Protein" 4.1,
"Fat": 16.4,
"Carbs"54.6,

"food": "cupcake",
"Measure": "1/2 cup",
"FoodAr" "كاب كيك",
"Grams": 100,
"MeasureAr":  "1/2 كوب",
"Calories": 369,
"Protein" 2.84,
"Fat": 10.93,
"Carbs": 67.64,

"food": "deviled egg",
"Measure": "1/2 egg",
"FoodAr":"بيضه شيطانيه",
"Grams": 100,
"MeasureAr":  "1/2 بيضه",
"Calories": 201,
"Protein" 11.57,
"Fat": 16.23,
"Carbs": 1.35,

"food": "Donuts",
"Measure": "1/2 piece",
"FoodAr":"دوناتس",
"Grams": 100,
"MeasureAr":  "1/2 قطعه",
"Calories": 412,
"Protein" 5.7g,
"Fat": 22.85,
"Carbs": 47,

"food": "Eggs benedict",
"Measure": "1/2 piece",
"FoodAr":"بيض بنديكت",
"Grams": 100,
"MeasureAr":  "1/2 قطعه",
"Calories": 276,
"Protein" 11.96,
"Fat": 21.6,
"Carbs": 8.32,

"food": "falafel",
"Measure": "6 piece",
"FoodAr":"فلافل",
"Grams": 100,
"MeasureAr":  "6 قطعه",
"Calories": 333,
"Protein" 13.31,
"Fat": 17.8,
"Carbs": 31.31,

"food": "fish and chips",
"Measure": "1 dish",
"FoodAr":"السمك والبطاطس المقليه",
"Grams": 100,
"Measure Ar": "واحد طبق",
"Calories": 300,
"Protein" 14,
"Fat": 12,
"Carbs": 33,

"food": "french fries",
"Measure": "20 piece"
"Foodar":"البطاطس المقليه",
"Grams": 100,
"Measure Ar":  "20 قطعه",
"Calories": 274,
"Portein" 3.48,
"Fat": 14.06,
"Carbs": 35.66,

"Food": "french onion soup",
"Measure":"1 cup",
"FoodAr":"شوربه البصل الفرنسيه",
"measureAr": "1كوب",
"Grams": 100,
"Calories": 153,
"Protein": 6.6,
"Carbs" :16.32,

"Food": "fried rice",
"Measure":"1 cup",
"FoodAr":"الارز المقلي",
"measureAr": "1كوب",
"Grams": 100,
"Calories": 168,
"Protein": 6.3,
"Carbs" :21.06,

"Food": "hamburger",
"Measure":"1/2 piece",
"FoodAr":"هامبورغر"
"measureAr": "1/2قطعه",
"Grams": 100,
"Calories": 254,
"Protein": 17.17,
"Carbs" : 0,

"Food": "Hot and sour soup",
"Measure":"1 cup",
"FoodAr":"شوربه ساخنه وحامضه"
"measureAr": "1كوب",
"Grams": 100,
"Calories": 67,
"Protein": 6.19,
"Carbs" : 2.03,

"Food": "Hotdog",
"Measure":"1 sandwich",
"FoodAr":"هوت دوج"
"measureAr": "1 سندوتش",
"Grams": 100,
"Calories": 247,
"Protein": 10.6,
"Carbs" : 18.4,

"Food": "ice cream",
"Measure":"1 cup",
"FoodAr": "ايس كريم",
"measureAr": "1كوب",
"Grams": 100,
"Calories": 201,
"Protein": 3.52,
"Carbs" : 24.4,

"Food": "macroni and cheese",
"Measure":"1 cup",
"FoodAr": "مكرونه بالجبن",
"measureAr": "1كوب",
"Grams": 100,
"Calories": 203,
"Protein": 7.94,
"Carbs" : 21.46,

"Food": "macrons",
"Measure":"1 piece",
"FoodAr": "ماكرون",
"measureAr": "1قطعه",
"Grams": 100,
"Calories": 456,
"Protein": 9,
"Carbs" : 50,

"Food": "Nachos",
"Measure":"1 cup",
"FoodAr": "ناتشوز",
"measureAr": "1كوب",
"Grams": 100,
"Calories": 343,
"Protein": 8,
"Carbs" : 34.9,

"Food": "omelette"
"Measure":"1 piece",
"FoodAr": "عجه البيض",
"measureAr": "1قطعه",
"Grams": 100,
"Calories": 153,
"Protein": 10.62,
"Carbs" : 0.69,

"Food": "onion rings"
"Measure": 3/4 piece",
"FoodAr": "حلقات البصل",
"measureAr": "3/4قطعه",
"Grams": 100,
"Calories": 332,
"Protein": 4.46,
"Carbs" : 37.74,
"food": "pizza",
"Measure": "1 slice",
"MeasureAr": "1 شريحه",
"FoodAr": "بيتزا",
"Grams": 100,
"Calories": 276,
"Protein":12.33,
"Fat": 11.74,
"Carbs": 30.33,

"food": "waffles",
"Measure": "1 piece",
"MeasureAr": "1 قطعه",
"FoodAr": "بسكويتات الوفل",
"Grams": 100,
"Calories": 310
"Protein":7.3,
"Fat": 9.55,
"Carbs": 48.84,